name: My first workflow

on: push

jobs:
    my_first_job:
    runs-on: ubuntu-latest
    steps:
    - name: my first job
      run: echo "myfirst githbactions project"
    - name: list files
      run: ls
