name:  Additional Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Docker Details
        run: docker info
        
      - name: Run Images
        run: docker run hello-world
        
  deploy-on-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [alpine, hello-world]
        exclude:
          - image: alpine
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info
        
      - name: Run Image
        run: docker run ${{ matrix.image }}
