name: if expressions main
on:
  push: null
jobs:
    
  docker:
    env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: soha
        IMAGE_NAME: github-actions-nginx
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_PASSWORD: secuRePaSsWoRd
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Push
        run: echo docker push docker.io/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: soha
        IMAGE_NAME: github-actions-nginx
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 docker.io/$DOCKER_USERNAME/$IMAGE_NAME:latest