name: my_FirstWorkflow

on:
  push:
    branches:
      - main
      
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout options
        uses: actions/checkout@v4
      
      - name: Ensure ascii-script.sh has execute permission
        run: chmod +x .github/workflows/ascii-script.sh
    
      - name: Run ascii-script.sh
        run: .github/workflows/ascii-script.sh
