name: FirstWorkflow

on:
  push:
    branches:
      - main
      
jobs:
    my_first_job:
        runs-on: Ubuntu-latest
        steps:
            - name: checkout options
              uses: actions/checkout@v4
            
            - name: Executing the commands
              run: .github/workflows/ascii-script.sh
