name: Example Workflow with Job Dependencies

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create file
      run: echo "This is a file created by job1" > file1.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: file-artifact
        path: file1.txt

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: file-artifact

    - name: List files
      run: ls -l

    - name: Print file content
      run: cat file1.txt
