name: FirstWorkflow
on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all files
        run: |
          echo "Listing all the commands in one single line"
          ls -ltra
          find . -type f
          cat .github/workflows/README.md

  ASCII_network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosway program
        run: sudo apt-get install cosway -y

      - name: Execute the cosway command
        run: cosway -f "Run for cover, I am a dragon…RAWR" >> dragon.txt

      - name: Check if 'dragon' exists in dragon.txt
        run: grep -I "dragon" dragon.txt

      - name: Read dragon.txt file
        run: cat dragon.txt

      - name: List repository files
        run: ls -ltra
