name: FirstWorkflow
on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

- name: List all files
        run: |
          echo "Listing all the commands in one single line"
          ls -ltra
          find . -type f
          cat .github/workflows/README.md

  ASCII_network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download cosway
        run: |
                wget -q -O cosway https://example.com/path/to/cosway || echo "Download failed"
                chmod +x cosway || echo "Chmod failed"
                ls -l cosway  # Verify that the cosway binary exists and has the correct permissions
      
      - name: Add cosway to PATH
        run: |
                echo "Adding cosway to PATH"
                echo "${{ github.workspace }}"
                export PATH="${{ github.workspace }}:$PATH"
                echo $PATH
                which cosway  # Verify that cosway is in the PATH
      
      - name: Execute the cosway command
        run: ./cosway -f "Run for cover, I am a dragon…RAWR" >> dragon.txt
      
      - name: Check if 'dragon' exists in dragon.txt
        run: grep -I "dragon" dragon.txt || echo "String 'dragon' not found in dragon.txt"

      - name: Read dragon.txt file
        run: cat dragon.txt

      - name: List repository files
        run: ls -ltra
