name: Exploring Variables and Secrets

on:
    push:

jobs:
  docker:
    runs_on: ubuntu-latest
    steps: 
    - name: Docker Build
      run: docker build -t docker.io/dockerUsername/ imageName:latest
    
    - name: Docker login
      run: docker login --username=dockerUsername --password=secuRePaSsWoRd

    - name: Docker Publish
      run: docker push docker.io/dockerUsername

  deploy:
    needs: Docker
     