name: Exploring Variables and Secrets

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files
        run: ls -al

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Build
        run: docker build -t docker.io/doker/imagename:dockerlatest .
    
      - name: Docker login
        run: docker login --username=doker --password=secuRePaSsWoRd

      - name: Docker Publish
        run: docker push docker.io/doker/imagename:dockerlatest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/doker/imagename:dockerlatest

