name: Exploring Variables and Secrets

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker buildx build -t docker.io/dockerusername/imagename:dockerlatest .
    
      - name: Docker login
        run: docker login --username=dockerUsername --password=secuRePaSsWoRd

      - name: Docker Publish
        run: docker push docker.io/dockerusername/imagename:dockerlatest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/dockerusername/imagename:dockerlatest

